fuhrysteve/marshmallow-jsonschema

marshmallow_jsonschema/base.py, tests/test_dump.py
_Missing is considered private API
=> Use singleton missing value rather than _Missing

.travis.yml, Makefile, marshmallow_jsonschema/base.py, marshmallow_jsonschema/validation.py, setup.py, tests/__init__.py, tests/test_dump.py
* Makes `_from_python_type` and `_from_nested_schema` classmethods so they can be overloaded
* Adds JSON Schema support for the following Marshmallow validators:
* `marshmallow.validate.OneOf`
* `marshmallow.validate.Range`
* `marshmallow.validate.Length`
* Adds tests for new validators
* Fixes a few PEP 8 warnings
* Adds whitespace for better readablity
We've been using this library a lot for work and have been needing to monkey patch a lot of functionality into it for our needs, so I figured I might as well push this upstream. I probably have two more PRs coming for this library in the next few weeks so keep you're eyes peeled.
=> Add Marshmallow Validator Support

setup.py
* Adds an except around `OSError` for the conversion of the README from RST to MD. This is needed because, if PyPandoc is installed, but Pandoc is NOT, then this conversion fails with that exception and nothing gets installed!
* Install Pandoc.
* Install PyPandoc.
* Uninstall Pandoc.
* Try to install `marshmallow-jsonschema`.
* **BUG:** Fails with OSError.
=> Prevent PyPandoc failing install process.

.gitignore, marshmallow_jsonschema/base.py, tests/test_dump.py
@fuhrysteve this is a bit of a bold rework... I've used the 'definitions' scoping to help and this should now work with e.g. https://github.com/jdorn/json-editor/  (see e.g. [this fiddle](http://jeremydorn.com/json-editor/?schema=N4IgJgpgZglgdjALjA9nAziAXKAKgBQDkVJtRlEAbCbEA40gGnAnQGMAnGAB2TVvokazRAE9uNLCBQAjAFYQ2iEM24cUEjslZkQcAIYBbSeXGSQ6RFzgBzEAF9mbABYxKYDhDi6xE2vo4OfVEVECQIQ0wcEAASTyhaAGIAekhYBD4MZMFSezy85jjoJNToeCRULJyaeyAAA=&value=N4IgdghgtgpiBcIQBoQGMAWBLANgEwCcYwEBtAXQF8gAAA==&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction)) but unfortunately brutusin/json-forms doesn't support recursive schemas at the moment.
Note this branch includes #33 and #35 and therefore covers both #32 and #34
=> Supporting recursive nested schemas

marshmallow_jsonschema/base.py, tests/test_dump.py
Partially related to #38 and not fixed by #39 -- arbitrary metadata is not added to the serialized output (only description and title are) -- this PR fixes #46, and more generally solves #45
=> add field metadata to serialized definition

marshmallow_jsonschema/base.py
When you do a subclass of `JSONSchema` and a field is `Nested` it will be useful that the new JSONScheme will be the same type of the subclass.
=> Use __class__ attribute to create a JSONSchema form for Nested

marshmallow_jsonschema/validation.py, tests/test_dump.py
According to the marshmallow docs for [validate.OneOf], the enum choices and labels are iterables, not necessarily lists.
[validate.OneOf]: http://marshmallow.readthedocs.io/en/latest/api_reference.html#marshmallow.validate.OneOf
Fixes a bug where a valid Marshmallow schema run through marshmallow-jsonschema could generate an object that could not be serialized as JSON.
See [behavior without the patch](https://gist.github.com/erik/b50cefeeefd1efcab0aa79743109ea99) for details
=> Handle validate.oneOf(iterable)

marshmallow_jsonschema/base.py
New implementation based on version string rather than data structure details.
=> Handle nested schema classes in both Marshmallow 2.x and 3.x.

marshmallow_jsonschema/base.py
It looks like json-forms doesn't make any accomodations for multiple
types [1]. Resulting in `Nested(multiple=True)` schemas not rendering
(as of json-forms v1.6.3).
This small change keeps generated schemas valid, and enables some level
of compatibility.
Admittedly, This doesn't solve the issue when `required=False` on nested fields, but I'm not a competent JS developer, and can't submit a PR for json-forms.
[1] https://github.com/brutusin/json-forms/blob/fcd15f14a7e97003efb12a6b70856c8c582a077b/src/js/brutusin-json-forms.js#L1090
=> Fix to enable compatibility with brutusin/json-forms v1.6.3

marshmallow_jsonschema/base.py, marshmallow_jsonschema/compat.py, tests/__init__.py, tests/test_dump.py
Hi @fuhrysteve ! I took initiative and wanted to cleanup the tests first, if you don't mind. The changes are:
- Fix typo in `dot_data_backwards_compatible` function
- Remove unused test case class
- Improve formatting so as to clearly separate [Arrange-Act-Assert](https://github.com/testdouble/contributing-tests/wiki/Arrange-Act-Assert) stages.
- Most importantly, there were some tests without asserts whatsoever. I added them and as that lead to failing tests, improved those tests a little.
=> Cleanup tests

.pre-commit-config.yaml, .travis.yml, CONTRIBUTING.md, README.md, example/example.py, marshmallow_jsonschema/__init__.py, marshmallow_jsonschema/base.py, marshmallow_jsonschema/compat.py, marshmallow_jsonschema/validation.py, pyproject.toml, requirements-test.txt, setup.py, tests/__init__.py, tests/test_dump.py, tox.ini
This PR is a bit controversial as it touches code style formatting, but black seems to be de-facto industry format. I haven't had much experience with pre-commit hooks myself, so I've borrowed all the configuration and especially `CONTRIBUTING.md` instructions from marshmallow official repository and everything seems to be working smooth so far.
I do believe we need proper style formatting so that code style does not get in the way when working on large features.
Please tell if you have any thoughts/suggestions on this matter.
=> Use black to format source code and add pre-commit hooks for linting

.coveragerc, marshmallow_jsonschema/__init__.py, marshmallow_jsonschema/base.py, marshmallow_jsonschema/compat.py, tests/__init__.py, tests/test_dump.py, tox.ini
This adds an ability to specify `additionalProperties` value for generated jsonschema either via `Meta` class:
```
class Meta:
additional_properties = True/False
```
or for marshmallow 3 it can be deduced from `unknown` field: `additionalProperties` will be set to True for `unknown=INCLUDE`, to False for `unknown=RAISE` and an exception will be raised for `unknown=EXCLUDE` (as it is not possible to emulate such a behavior in jsonschema).
There is no automatic deduction for `additionalProperties` value for marshmallow 2, obviously.
=> `additionalProperties` support

marshmallow_jsonschema/base.py, tests/test_dump.py
Addresses #79 
Instead of simply running field's class against `mapping` keys, check whether field's class is a subclass of one of the `mapping` keys.
=> Get pytype by checking field's subclass

marshmallow_jsonschema/base.py
Addresses: #85 
Extends default mapping with an entry `marshmallow.fields.Number: decimal.Decimal`
=> Add support for marshmallow.fields.Number

.gitignore, marshmallow_jsonschema/base.py
`fields.LocalDateTime` was removed in marshmallow 3.0.0rc9 [(see link)](https://marshmallow.readthedocs.io/en/latest/changelog.html?highlight=LocalDateTime#rc9-2019-07-31), I just changed it to `fields.DateTime`.
I'm not going to pretend like I thoroughly checked the implications thought ...
Fixes #84
=> Quick fix for marshmallow 3.x compatibility

marshmallow_jsonschema/base.py
Addresses #83
Now, a user has an ability to modify JSON schema property name using `metadata['name']` parameter.
Ex., consider the following schema:
```
class ExampleSchema(Schema):
api_token = String(description='API token.')
```
Resulting JSON schema would look like this:
```
{
"$ref": "#/definitions/ExampleSchema",
"$schema": "http://json-schema.org/draft-07/schema#",
"definitions": {
"ExampleSchema": {
"additionalProperties": false,
"properties": {
"api_token": {
"description": "API token.",
"title": "api_token",
"type": "string"
}
},
"type": "object"
}
}
}
```
If a user desires to modify JSON schema property name (the part `"api_token": {`), one can simply add `name` parameter to the schema:
```
class ExampleSchema(Schema):
api_token = String(name='api-token', description='API …
```
=> Introduce ability to modify JSON schema property name

marshmallow_jsonschema/base.py
Hi @fuhrysteve ! #81 along with #86 introduced a bug that causes builds to fail. This PR fixes it.
#81 added sequential subclass check that iterated over the mapping from marshmallow types to python types. #86 added `fields.Number` as a key and `decimal.Decimal` as a corresponding value. Since only Python 3.6 introduced ordered dictionaries, in previous versions order was not guaranteed. 
This means that sometimes the keys in that dictionary were ordered in such a way that `fields.Number` came first. That meant that python type corresponding to `fields.Integer` became `decimal.Decimal` and not `int` as expected. As JSON schema output for `Decimal` and `int` differs too, that lead to failing tests.
Instead of dict I iterate over a tuple of tuples - this will guarantee the order of subclass …
=> Fix marshmallow type subclass check

.gitignore, marshmallow_jsonschema/base.py, marshmallow_jsonschema/validation.py, tests/test_dump.py, tests/test_validation.py
Hi @fuhrysteve !
I found one bug on dumping schemas with `Date` fields. In result of dump json schema field `Date` got wrong format `date-time`. It depend on order in tuple MARSHMALLOW_TO_PY_TYPES_PAIRS. I moved fields.DateTime after `fields.Time` and `fields.Date`.
1.  Was move rule for **datetime.datetime** to bottom on after rules of **datetime.date** and **datetime.time**.
2. I added handling for marshmallow Regexp validator.
3. I added boolean named argument **props_ordered** on **JSONSchema** class constructor. This allows to enable field order preservation in properties.
4. Allows using custom validators (based on marshmallow supported validators). Using class attribute **_jsonschema_base_validator_class** for indicate the base validator.
=> Fixed marshmallow type subclass check for datetime based classes, added few simple additional options

marshmallow_jsonschema/base.py, tests/test_dump.py
Support allow_none=True. This should allow us to close
https://github.com/fuhrysteve/marshmallow-jsonschema/pull/19
https://github.com/fuhrysteve/marshmallow-jsonschema/issues/101
=> Add support for allow_none and test

.travis.yml, CHANGES, README.md, pyproject.toml, requirements-test.txt, requirements.txt, setup.py, tox.ini
Python 3.5 is EOL September 13, 2020. pre-commit dropped support for it, and there appear to be [very few python 3.5](https://pypistats.org/packages/marshmallow-jsonschema) downloads. As such, I'm just going to get ahead of the curve and drop support for it now.
Python 3.5 should still work and I'll still accept patches for awhile!! We're just not officially supporting it anymore in the build.
=> bump dependency versions, drop python 3.5 support

README.md
>>> hex(5)
'0x5'
so rgb(1,2,33) will result in "#1221" which is strange
=> fix: buggy code in colors sample

CHANGES, marshmallow_jsonschema/base.py, requirements-test.txt, setup.py, tests/test_dump.py, tests/test_imports.py, tests/test_validation.py
Add optional support for marshmallow_union and marshmallow_enum.
This will provide useful integration with the [marshmallow_dataclass](https://github.com/lovasoa/marshmallow_dataclass) package which also utilises these packages and makes setting up marshmallow schemas easy.
=> Add support for marshmallow_union and marshmallow_enum

marshmallow_jsonschema/base.py, tests/test_dump.py
Add support for specifying the type of Dict values. Prior to this change any information about the values in a dict - particularly nested schemas - was lost.
=> Include type of Dict values

marshmallow_jsonschema/base.py
Added support for type IP of marshmallow fields, So it could be inside a marshmallow schema that will be translated to json schema using this library.
=> Added fields.IP marshmallow field type to python types mapping

marshmallow_jsonschema/base.py, tests/test_dump.py
A field has an optional `data_key` which can hold an alternative
output key name. When dumping a schema, the `data_key` should be
used instead of the name.
=> Use data_key when available for property names

marshmallow_jsonschema/base.py, tests/test_dump.py
So we need to check if a field inherits UUID before checking for String.
Signed-off-by: Andreas Stenius <andreas.stenius@svenskaspel.se>
=> The UUID field inherits from the String field

marshmallow_jsonschema/base.py, tests/test_dump.py
Change the `readonly` attribute to `readOnly` as per the Json Schema [specification](https://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.9.4).
=> fix: Change readonly to readOnly

marshmallow_jsonschema/base.py, tests/test_dump.py
This fixes two issues:
1. The default value for nested fields wasn't serialized.
2. The default value for other fields may be a callable and in that case it shouldn't be emitted into the schema.
Fixes #143
=> Fixes to field default

marshmallow_jsonschema/base.py, tests/test_dump.py, tests/test_validation.py
Since the json schema spec [allows](https://json-schema.org/understanding-json-schema/reference/numeric.html?highlight=integer#integer) for `integer` types, update the mappings to return `integer` types for marshmallow `Integer` fields.
=> set int to "integer" instead of "number"

marshmallow_jsonschema/base.py, tests/test_dump.py
also pass context to nested schema
this allows to create a json schema for a (nested) context-sensitive schema
closes #138
=> Pass marshmallow context into nested schema

marshmallow_jsonschema/base.py, tests/test_dump.py
=> 🐛 Fix `AttributeError` when nesting schemas using `lambda: Schema()`
